workflows:
    ios-app:
        name: iOS App
        environment:
            vars:
                XCODE_WORKSPACE: "Cocktails"
                XCODE_SCHEME: "Cocktails"
            xcode: latest
            cocoapods: default
        scripts:
            - xcodebuild build -workspace "Cocktails.xcworkspace" -scheme "Cocktails" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        artifacts:
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
